# accessible as site.*
title: "False Sharing"
description: "Aaron Becker's Online Stuff"
url: "http://falsesharing.com"
files: "http://falsesharing.com/files/" 
author: "Aaron Becker"
email: "aaron@falsesharing.com"

# --server --auto
server: true
auto: true

# default './_site'
destination: './_site'

# turn on pygment syntax highlighting
pygments: true

# pagination
# paginate: 8

## permalink style: http://wiki.github.com/mojombo/jekyll/permalinks
permalink: pretty

# use rdiscount for markdown
markdown: rdiscount

## maruku settings
#maruku:
#  png_dir: files/latex
#  png_url: /images/latex
